# Generated by Django 5.1.4 on 2025-01-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_is_clothing_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set(),
        ),
    ]
