# Generated by Django 5.1.4 on 2025-01-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_size_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size']},
        ),
    ]
