# Generated by Django 5.1.4 on 2025-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_color_alter_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price_difference',
            field=models.IntegerField(default=0),
        ),
    ]
