# Generated by Django 5.1.4 on 2025-01-04 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_size_price_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
