# Generated by Django 5.1.4 on 2025-01-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Discount',
            new_name='discount',
        ),
    ]
